# Generated by Django 5.1.4 on 2025-01-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_emp_comm_alter_emp_mgr_alter_emp_sal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='Hire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
